package com.ustglobal.exception.first;

public class TestC {

	public static void main(String[] args) {

		int[] a = {10,20,50,60};
		int b = 10;

		try {
			System.out.println(a[4]);
		}catch(ArrayIndexOutOfBoundsException ae) {
			System.out.println("Index is not Present");
		}
		try {
			System.out.println(b/0);
		}catch (ArithmeticException ae) {
			System.out.println("Nuber is dividd by Zero");
		}
	}
}
