package com.ustglobal.exception.first;

public class TestF {

	public static void main(String[] args) {

		System.out.println("Main Started");

		String s = "Hello";
		int[] a = {10,30,50};
		int b = 10;

		try {

			String s1 = s.toUpperCase();
			System.out.println(s1);
			System.out.println(a[2]);
			System.out.println(b/0);

		}catch (NullPointerException npe) {
			System.out.println("Dont Play With Null");

		}catch (ArrayIndexOutOfBoundsException aie) {
			System.out.println("Index is not Present");

		}catch (ArithmeticException ae) {
			System.out.println("Divide by Zero");
		}
		System.out.println("Main Ended");
	}

}
